[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/"
  to = "/claim.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/api/claim"
  to = "/.netlify/functions/claim"
  status = 200

[[redirects]]
  from = "/api/admin/*"
  to = "/.netlify/functions/admin-:splat"
  status = 200